##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.9.0-B19] date: [Sat May 23 01:53:45 ICT 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = STM32_TFLM


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Core/Src/system_stm32f4xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Core/Src/gpio.c \
Core/Src/usart.c \
Core/Src/spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c 

CXX_SOURCES = \
App/HelloWorld/constants.cc \
Models/sine_model_data.cc \
Core/Src/main.cpp \
Core/Src/debug_log.cc \
TFLM/tensorflow/compiler/mlir/lite/core/api/error_reporter.cc \
TFLM/tensorflow/lite/core/api/flatbuffer_conversions.cc \
TFLM/tensorflow/lite/core/api/tensor_utils.cc \
TFLM/tensorflow/lite/core/c/common.cc \
TFLM/tensorflow/lite/micro/micro_allocator.cc \
TFLM/tensorflow/lite/micro/tflite_bridge/micro_error_reporter.cc \
TFLM/tensorflow/lite/micro/micro_interpreter.cc \
TFLM/tensorflow/lite/micro/system_setup.cc \
TFLM/tensorflow/lite/micro/micro_interpreter_graph.cc \
TFLM/tensorflow/lite/micro/micro_log.cc \
TFLM/tensorflow/lite/micro/micro_resource_variable.cc \
TFLM/tensorflow/lite/micro/kernels/kernel_util.cc \
TFLM/tensorflow/lite/micro/memory_helpers.cc \
TFLM/tensorflow/lite/micro/tflite_bridge/flatbuffer_conversions_bridge.cc \
TFLM/tensorflow/lite/micro/flatbuffer_utils.cc \
TFLM/tensorflow/lite/micro/micro_interpreter_context.cc \
TFLM/tensorflow/lite/micro/micro_context.cc \
TFLM/tensorflow/lite/micro/micro_op_resolver.cc \
TFLM/tensorflow/lite/micro/micro_allocation_info.cc \
TFLM/tensorflow/lite/micro/arena_allocator/single_arena_buffer_allocator.cc \
TFLM/tensorflow/lite/micro/memory_planner/greedy_memory_planner.cc \
TFLM/tensorflow/lite/micro/memory_planner/linear_memory_planner.cc \
TFLM/tensorflow/lite/micro/kernels/fully_connected.cc \
TFLM/tensorflow/lite/micro/kernels/fully_connected_common.cc \
TFLM/tensorflow/lite/kernels/kernel_util.cc \
TFLM/tensorflow/lite/kernels/internal/quantization_util.cc \
TFLM/tensorflow/lite/kernels/internal/portable_tensor_utils.cc \
TFLM/tensorflow/lite/kernels/internal/common.cc \
BSP/LCD/lcd.cpp \
TFLM/tensorflow/compiler/mlir/lite/schema/schema_utils.cc


# ASM sources
ASM_SOURCES =  \
startup_stm32f407xx.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
CXX = $(PREFIX)g++
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F407xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IModels \
-IApp/HelloWorld \
-ITFLM \
-ITFLM/tensorflow \
-ITFLM/tensorflow/lite/micro/tools/make/downloads/flatbuffers/include \
-ITFLM/tensorflow/lite/micro/tools/make/downloads/gemmlowp \
-ITFLM/tensorflow/lite/micro/tools/make/downloads/ruy \
-IBSP/LCD \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
# C objects
OBJECTS = $(patsubst %.c,$(BUILD_DIR)/%.o,$(C_SOURCES))

# C++ objects
OBJECTS += $(patsubst %.cpp,$(BUILD_DIR)/%.o,$(filter %.cpp,$(CXX_SOURCES)))
OBJECTS += $(patsubst %.cc,$(BUILD_DIR)/%.o,$(filter %.cc,$(CXX_SOURCES)))

# ASM objects
OBJECTS += $(patsubst %.s,$(BUILD_DIR)/%.o,$(ASM_SOURCES))
OBJECTS += $(patsubst %.S,$(BUILD_DIR)/%.o,$(ASMM_SOURCES))

$(BUILD_DIR)/%.o: %.c Makefile
	mkdir -p $(dir $@)
	$(CC) -c $(CFLAGS) \
	-Wa,-a,-ad,-alms=$(basename $@).lst \
	$< -o $@

$(BUILD_DIR)/%.o: %.cpp Makefile
	mkdir -p $(dir $@)
	$(CXX) -c $(CFLAGS) -fno-rtti -fno-exceptions \
	-Wa,-a,-ad,-alms=$(basename $@).lst \
	$< -o $@

$(BUILD_DIR)/%.o: %.cc Makefile
	mkdir -p $(dir $@)
	$(CXX) -c $(CFLAGS) -fno-rtti -fno-exceptions \
	-Wa,-a,-ad,-alms=$(basename $@).lst \
	$< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@
$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(shell find $(BUILD_DIR) -name "*.d" 2>/dev/null)

# *** EOF ***
